import asyncio
import json
from pathlib import Path

import httpx
from fastapi.testclient import TestClient

from app.application.graph_service import ProjectGraphService
from app.application.readme_service import ReadmeService, detect_commands
from app.domain.readme_models import ReadmeEnhancement
from app.infrastructure.openrouter_client import OpenRouterClient
from app.infrastructure.output_directory import ensure_output_directory
from app.main import create_app
from tests.test_graph_service import create_mixed_project, write


class SuccessfulReadmeProvider:
    model = "deepseek/deepseek-v4-flash"

    async def enhance_readme(self, **kwargs) -> ReadmeEnhancement:
        modules = kwargs["modules"]
        return ReadmeEnhancement(
            overview="Enhanced project overview.",
            architecture="Enhanced architecture narrative.",
            module_summaries={modules[0].name: "Enhanced module summary."},
            rationale="DeepSeek improved prose from graph metadata.",
        )


class FailingReadmeProvider:
    model = "deepseek/deepseek-v4-flash"

    async def enhance_readme(self, **kwargs) -> ReadmeEnhancement:
        raise RuntimeError("provider unavailable")


def build_service(root: Path, provider=None) -> ReadmeService:
    create_mixed_project(root)
    write(
        root / "package.json",
        json.dumps(
            {
                "packageManager": "pnpm@10.22.0",
                "scripts": {
                    "dev": "vite",
                    "test": "vitest",
                    "build": "vite build",
                },
            }
        ),
    )
    paths = ensure_output_directory(root)
    graph = ProjectGraphService.create(root, paths)
    graph.scan()
    return ReadmeService(paths, lambda: graph.document, provider)


def test_offline_readme_uses_graph_and_writes_artifact(tmp_path: Path) -> None:
    service = build_service(tmp_path)

    result = asyncio.run(service.generate("A local code graph for builders."))

    assert result.mode == "offline"
    assert result.model is None
    assert result.overview == "A local code graph for builders."
    assert "frontend/src/main.tsx" not in result.entrypoints
    assert result.key_files
    assert "pnpm dev" in result.commands
    assert result.warnings == (
        "frontend/src/lib/api.ts could not resolve ./missing.",
    )
    assert result.mermaid.startswith("flowchart TD")
    assert len(result.key_files) <= 10
    artifact = tmp_path / ".vibegraph" / "README.generated.md"
    assert artifact.is_file()
    markdown = artifact.read_text(encoding="utf-8")
    assert "# " + tmp_path.name in markdown
    assert "## Mermaid Diagram" in markdown
    assert "```mermaid" in markdown
    assert "## Generated by VibeGraph" in markdown


def test_readme_selects_entrypoints_and_bounded_internal_edges(
    tmp_path: Path,
) -> None:
    service = build_service(tmp_path)
    write(
        tmp_path / "frontend" / "src" / "main.tsx",
        'import App from "./App";\nexport const main = App;\n',
    )
    graph = ProjectGraphService.create(tmp_path, service.output_paths)
    graph.scan()
    service.graph_loader = lambda: graph.document

    result = asyncio.run(service.generate())

    assert "frontend/src/main.tsx" in result.entrypoints
    assert "unresolved:./missing" not in result.mermaid
    assert result.mermaid.count("-->") <= 14


def test_readme_reports_missing_symbols_and_avoids_unverified_ts_command(
    tmp_path: Path,
) -> None:
    write(
        tmp_path / "main.ts",
        'import { missing } from "./service";\nexport const main = missing;\n',
    )
    write(tmp_path / "service.ts", "export const available = true;\n")
    paths = ensure_output_directory(tmp_path)
    graph = ProjectGraphService.create(tmp_path, paths)
    graph.scan()
    service = ReadmeService(paths, lambda: graph.document)

    result = asyncio.run(service.generate())

    assert result.warnings == (
        "main.ts imports missing from service.ts, but missing is not exported.",
    )
    assert detect_commands(tmp_path, ("main.ts",)) == ()


def test_provider_enhances_only_readme_prose(tmp_path: Path) -> None:
    offline = build_service(tmp_path / "offline")
    enhanced = build_service(
        tmp_path / "enhanced", SuccessfulReadmeProvider()
    )

    offline_result = asyncio.run(offline.generate())
    enhanced_result = asyncio.run(enhanced.generate())

    assert enhanced_result.mode == "enhanced"
    assert enhanced_result.overview == "Enhanced project overview."
    assert enhanced_result.architecture == "Enhanced architecture narrative."
    assert enhanced_result.key_files == offline_result.key_files
    assert enhanced_result.commands == offline_result.commands
    assert enhanced_result.mermaid == offline_result.mermaid


def test_provider_failure_preserves_deterministic_readme(tmp_path: Path) -> None:
    service = build_service(tmp_path, FailingReadmeProvider())

    result = asyncio.run(service.generate())

    assert result.mode == "fallback"
    assert result.key_files
    assert "failed" in result.provider_message.lower()
    assert "using `deepseek/deepseek-v4-flash`" not in result.markdown


def test_readme_api_works_without_key(tmp_path: Path) -> None:
    create_mixed_project(tmp_path)
    with TestClient(
        create_app(
            project_root=tmp_path,
            environment={},
            watcher_enabled=False,
        )
    ) as client:
        response = client.post(
            "/api/readme",
            json={"description": "A graph-derived project guide."},
        )

    assert response.status_code == 200
    payload = response.json()
    assert payload["mode"] == "offline"
    assert payload["overview"] == "A graph-derived project guide."
    assert payload["artifactPath"] == ".vibegraph/README.generated.md"
    assert (tmp_path / payload["artifactPath"]).is_file()


def test_openrouter_readme_payload_excludes_source_and_absolute_paths(
    tmp_path: Path,
) -> None:
    captured: dict[str, object] = {}

    async def handler(request: httpx.Request) -> httpx.Response:
        captured["body"] = json.loads(request.content)
        return httpx.Response(
            200,
            json={
                "choices": [
                    {
                        "message": {
                            "content": json.dumps(
                                {
                                    "rationale": "Metadata-only enhancement.",
                                    "overview": "Enhanced overview.",
                                    "architecture": "Enhanced architecture.",
                                    "modules": [],
                                }
                            )
                        }
                    }
                ]
            },
        )

    private_root = tmp_path / "private-project"
    graph_service = build_service(private_root)
    document = graph_service.graph_loader()
    client = OpenRouterClient(
        api_key="secret-test-key",
        transport=httpx.MockTransport(handler),
    )
    result = asyncio.run(
        client.enhance_readme(
            project_name="project",
            description="",
            document=document,
            modules=(),
            entrypoints=(),
            key_files=("backend/app/api/auth.py",),
            commands=("pnpm dev",),
            warnings=(),
        )
    )

    body_text = json.dumps(captured["body"])
    assert result.overview == "Enhanced overview."
    assert "backend/app/api/auth.py" in body_text
    assert "def login" not in body_text
    assert str(private_root) not in body_text
